name: Clang
on:
  push:
  workflow_dispatch:

jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: sw_vers
      - run: xcode-select --print-path
      - run: clang --version
      - run: ./clang-test.sh
