name: Test
on:
  push:
  workflow_dispatch:
jobs:
  macos:
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - run: sw_vers
      - run: xcode-select --print-path
      - run: uname -a
      - run: sysctl -a
      - run: system_profiler -detailLevel full -xml > details.spx
      - run: df -h
      - uses: actions/upload-artifact@v4
        with:
          name: system profiler output (${{ matrix.os }})
          path: details.spx
      - name: install speedtest
        run: |
          brew tap teamookla/speedtest
          brew update
          brew install speedtest
      - run: speedtest --accept-license

  ubuntu:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - run: uname -a
      - run: cat /proc/cpuinfo
      - run: lscpu
      - run: sudo lshw -html > lshw.html
      - run: df -h
      - uses: actions/upload-artifact@v4
        with:
          name: lshw output (${{ matrix.os }})
          path: lshw.html
      # - run: hwinfo
      - name: install speedtest
        run: |
          curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
          sudo apt install speedtest -y
      - run: speedtest --accept-license
