name: Test
on:
  push:
  workflow_dispatch:
concurrency:
  cancel-in-progress: true
jobs:
  macos:
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - run: sw_vers
      - run: xcode-select --print-path
      - run: plutil -p ~/Library/Preferences/com.apple.dt.Xcode.plist
      - run: uname -a
      - run: sysctl -a
      - run: system_profiler -detailLevel full -xml > details.spx
      - run: df -h
      - uses: actions/upload-artifact@v4
        with:
          name: system profiler output (${{ matrix.os }})
          path: details.spx
      - run: curl -v https://mensura.cdn-apple.com/api/v1/gm/config
      - run: networkQuality -v
      - name: install speedtest tcping
        run: |
          brew tap teamookla/speedtest
          brew tap pouriyajamshidi/tap
          brew update
          sed -i '' 's/2.6.0/2.7.0/g' "$(brew formula pouriyajamshidi/tap/tcping)"
          brew install speedtest pouriyajamshidi/tap/tcping
      - run: speedtest --accept-license
      - run: ping -c 20 1.1.1.1 || true
      - run: ping -c 20 8.8.8.8 || true
      - run: ping -c 20 updates.cdn-apple.com || true
      - run: tcping -c 20 1.1.1.1 443
      - run: tcping -c 20 8.8.8.8 443
      - run: tcping -c 20 updates.cdn-apple.com 443

  ubuntu:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, ubuntu-24.04-arm, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - run: uname -a
      - run: cat /proc/cpuinfo
      - run: lscpu
      - run: sudo lshw -html > lshw.html
      - run: df -h
      - uses: actions/upload-artifact@v4
        with:
          name: lshw output (${{ matrix.os }})
          path: lshw.html
      # - run: hwinfo
      - run: curl -v https://mensura.cdn-apple.com/api/v1/gm/config
      - name: add repo
        if: matrix.os != 'ubuntu-24.04' && matrix.os != 'ubuntu-24.04-arm'
        run: |
          curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
      - name: add repo
        if: matrix.os == 'ubuntu-24.04' || matrix.os == 'ubuntu-24.04-arm'
        run: |
          curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo os=ubuntu dist=jammy bash
      - name: download tcping
        if: matrix.os != 'ubuntu-24.04-arm' && matrix.os != 'ubuntu-22.04-arm'
        run: |
          curl -Ls https://github.com/pouriyajamshidi/tcping/releases/latest/download/tcping-amd64.deb -o /tmp/tcping.deb
      - name: download tcping
        if: matrix.os == 'ubuntu-24.04-arm' || matrix.os == 'ubuntu-22.04-arm'
        run: |
          curl -Ls https://github.com/pouriyajamshidi/tcping/releases/latest/download/tcping-arm64.deb -o /tmp/tcping.deb
      - name: install speedtest tcping
        run: |
          sudo apt install speedtest /tmp/tcping.deb -y
      - run: speedtest --accept-license
      - run: ping -c 20 1.1.1.1 || true
      - run: ping -c 20 8.8.8.8 || true
      - run: ping -c 20 updates.cdn-apple.com || true
      - run: tcping -c 20 1.1.1.1 443
      - run: tcping -c 20 8.8.8.8 443
      - run: tcping -c 20 updates.cdn-apple.com 443

  windows:
    strategy:
      matrix:
        os: [windows-2025, windows-2022, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - run: curl.exe -v https://mensura.cdn-apple.com/api/v1/gm/config
      - name: install speedtest tcping
        run: |
          winget settings --enable LocalManifestFiles
          winget install --id=Ookla.Speedtest.CLI -e
          curl.exe -LO 'https://raw.githubusercontent.com/microsoft/winget-pkgs/31a68e3303a70965319c143752261975d8e7989a/manifests/p/pj/tcping/2.7.0/pj.tcping.installer.yaml
          winget install --manifest pj.tcping.installer.yaml
      - run: speedtest --accept-license
      - run: ping -n 20 1.1.1.1
      - run: ping -n 20 8.8.8.8
      - run: ping -n 20 updates.cdn-apple.com
      - run: tcping -c 20 1.1.1.1 443
      - run: tcping -c 20 8.8.8.8 443
      - run: tcping -c 20 updates.cdn-apple.com 443

